name: Build and Test with Pip & Pytest

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/pip-build-test.yml"
      - "CMakeLists.txt"
      - "cmake/**"
      - "core/**"
      - "py_utils/**"
      - "pyms3d/**"
      - "testing/**"
      - "pyproject.toml"
      - "pytest.ini"
  pull_request:
    branches: [ "main" ]
    paths: 
      - ".github/workflows/pip-build-test.yml"
      - "CMakeLists.txt"
      - "cmake/**"
      - "core/**"
      - "py_utils/**"
      - "pyms3d/**"
      - "testing/**"
      - "pyproject.toml"
      - "pytest.ini"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest]
        build_type: [Release]
        c_compiler: [gcc]
        cpp_compiler: [g++]
        python-version: ['3.8', '3.11']

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install OpenCL
      run: sudo apt-get install -y ocl-icd-opencl-dev pocl-opencl-icd

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install
      # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      run: |
        CXX=${{ matrix.cpp_compiler }} pip install .
        pip install pytest

    - name: Download Test Data
      run: |
        wget -O ./testing.7z https://vgl.csa.iisc.ac.in/mscomplex/data/testing.7z
        7z x ./testing.7z -o${{ github.workspace }}/testing -y
        ls -la testing/

    - name: Test
      run: pytest -v .